[build]
builder = "NIXPACKS"
buildCommand = "npm install --include=dev && (cd frontend && npm install --include=dev) && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
